### PR TITLE
feat: rds

### PR DESCRIPTION
**Pull request by sjedlikowski**
PostgreSQL database in a private subnet.
It's missing a security group, but we can add it when we'll have the ECS ready.
More detailed logging is disabled because the cost of it is not easy to calculate - it's all covered by CloudWatch, but at the moment we don't know how much more logs will it produce.

### CODE REVIEW

**Review by wojtekk — APPROVED** [review]
LGTM

**Comment by wojtekk** [comment]
@sjedlikowski have you created this resource?

**Comment by sjedlikowski** [comment]
No, I was waiting for a review. But I'll do it in a few minutes.

**Comment by sjedlikowski** [comment]
Done.

**Pull request merged**
